name: simple_responsive
description: "A Flutter package to make your app responsive according to a reference resolution device or size percentage from the real device."
version: 1.0.1
homepage: https://github.com/ArZHa03/simple_responsive

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0